### ISSUE TITLE
error when compile aosp

### ISSUE THREAD

**Issue by pmrk74** [sonyxperiadev/device-sony-loire#157]
i downloaded aosp oreo source but when compile the source after compile 89% have a problem:

```

ninja: build stopped: subcommand failed.
11:22:26 ninja failed with: exit status 1
build/core/main.mk:21: recipe for target 'run_soong_ui' failed
make: *** [run_soong_ui] Error 1
```

**Comment by jerpelea** [comment]
please run repo_sync.sh and start compilation after

**Comment by pmrk74** [comment]
how run repo_sync.sh?

**Comment by jerpelea** [comment]
it is in tfe root of your repo folder

**Comment by pmrk74** [comment]
i not have arepo folder

i just have a repo.sh on bin folder

**Comment by jerpelea** [comment]
please start again foolowing the build guide
https://developer.sonymobile.com/open-devices/
after the initial repo sync in your android folder you should have  repo_update.sh 
by running this script you will cherrypick all needed patches from upstream

**Comment by pmrk74** [comment]
i do it but again:
```
[  0% 8/15738] host C++: adb <= system/core/adb/commandline.cpp
ninja: build stopped: subcommand failed.
14:02:37 ninja failed with: exit status 1
build/core/main.mk:21: recipe for target 'run_soong_ui' failed
make: *** [run_soong_ui] Error 1
```

**Comment by jerpelea** [comment]
since i can not reproduce the issue i would suggezt to
1. check your ubuntu installation
2. download sources again

**Comment by pmrk74** [comment]
i tested ubuntu 16.04 and 17.04 but got it wrong

The third time I download the source

**Comment by jerpelea** [comment]
please use https://github.com/sonyxperiadev/bug_tracker for future issues

**Comment by belov555** [comment]
system/sepolicy/Android.mk:79: warning: BOARD_SEPOLICY_VERS not specified, assuming current platform version
[947/948] including vendor/qcom/opensource/location/Android.mk ...
build/make/core/base_rules.mk:244: error: vendor/qcom/opensource/location/loc_api/ds_api: MODULE.TARGET.SHARED_LIBRARIES.libloc_ds_api already defined by vendor/qcom/opensource/location/ds_api.
23:08:32 ckati failed with: exit status 1
Each time different errors

**Comment by bartcubbins** [comment]
@belov555 this issue is not related to loire platform
