### ISSUE TITLE
Random reboots to 'Android' logo. Possibily due to Wi-FI [oreo 8.0.0_r15]

### ISSUE THREAD

**Issue by bamsbamx** [sonyxperiadev/device-sony-loire#172]
I have built AOSP sources (not modified) from sonyxperiadev using the following guide [https://developer.sonymobile.com/open-devices/aosp-build-instructions/how-to-build-aosp-oreo-for-unlocked-xperia-devices/](url) with commits updated to 6th November

However, the phone reboots from time to time to Android logo (soft-reboot) by itself. It seems it happens under 2 conditions:

1. Have Wi-Fi turned ON (not sure if has to be connected to any network) (WiFI turned OFF -> no reboot)
2. Leave the phone with screen OFF for some time (maybe until entering Wakelock?)
3. Not be plugged in to charger

After some time, the device reboots into Android logo and will be stuck there until hard reboot (VolUp + Power for some seconds). After that, the device will boot without any problem

Here I leave logcats via attached file or via gist (you can see the problem after line 7224, although there are more errrors some lines before that). In the logs, you can see "beggining of main" in line 8212 due to the reboot:

- https://gist.github.com/bamsbamx/010150781a961e71c29f3a83ffbf8c0c

- [logs.txt](https://github.com/sonyxperiadev/device-sony-loire/files/1453001/logs.txt)

Maybe related to the problem: when accessing Wi-FI section in Settings, the app will ANR and close by itself

**Comment by jerpelea** [comment]
please use the bug tracker
https://github.com/sonyxperiadev/bug_tracker
